language: python
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "What tests?! This is a hackathon!"
deploy:
  provider: heroku
  api_key:
    secure: "LyQpdqESFeLpvZiMEyziN+16c9y0LnyRgfYwS+afSOjo52MlmqDxP7iOZDXbdNlX4eVkN30gU2blbiPeZM+moqZPMPUy4CTKNauO9h9+ot94/W8tlCUeJC5SM29lDA9IaMDbOYFaP4aWeaM33NOkNiB7muUq0KxZksJakm+76hqHGFBnYWPrPEAHg2Kpf0kGy8cbbeOEkGIG54+PNk9Z1L7nfOEPFK7dk9khcxyEQJHREtsxjhVv6rdyU1ZXlLWtfEhWz90L/QJEjI9M4F++jWYlXKwan4ty5Jp7841FzK4h9eJV9xwUEXZBAWsRfwC/EQSQBhFMSJVP1uanWM1dnDmV/GWGhGMkYbcocoNmBI7fQBUgPnOnGgXvirDgBa3YmDjijeeBun8+7Q2Pf8Fc7Ruo24co0hX6Su2XAqKR4+snZrVWEDSFtgf90tgiovwoEHmbYtwRj7Cpkb+Rv3kkD2kzgvGAeYYXWB/IinC5q1yVsatFukTTXKxnd2zUSetpTQmNAW5+4ultKKCnItbwMsh9YhaG8Yrp65geWBr5jHwEe2OQhG19d6ENwV+jsLyHraXJp/GqJnDHGUSkCzb1BhIfflYp1pw+lQcEv7DpHHfiLiaq14Py8CusnEhfRO+hcbE0BiEN4ZCA/mGVnNgp/yVUsQuZiqNRGL8uhdkWldI="
  app: lexii-backend
